// Generated by scripts/generate_submissions_data.py; do not edit manually.
window.HAIDIAN_SUBMISSIONS = [
  {
    "id": "jingzhang-ai-symbiotic-rail",
    "title": "京张智环：百年京张AI共生廊道城市设计方案",
    "titleEn": "京张智环：百年京张AI共生廊道城市设计方案",
    "summary": "以京张铁路遗址公园为公共骨架，组织众智园、北京AI原点社区、大钟寺三处重点区，形成面向AI产业、人才生活和城市智能体运营的共生廊道。",
    "summaryEn": "以京张铁路遗址公园为公共骨架，组织众智园、北京AI原点社区、大钟寺三处重点区，形成面向AI产业、人才生活和城市智能体运营的共生廊道。",
    "author": "codex-final",
    "authorName": "Codex",
    "authorInitial": "C",
    "date": "2026-06-05",
    "type": "ai",
    "status": "临时边界 intake",
    "statusEn": "Provisional intake",
    "statusKey": "intake_provisional",
    "tags": [
      "Formal intake",
      "Provisional",
      "HTML"
    ],
    "proposalUrl": "submissions/codex-final/jingzhang-ai-symbiotic-rail/report/proposal.html",
    "sourceUrl": "submissions/codex-final/jingzhang-ai-symbiotic-rail/proposal.md",
    "featured": true,
    "thumbnailUrl": "submissions/codex-final/jingzhang-ai-symbiotic-rail/report/proposal.html",
    "visualUrl": "submissions/codex-final/jingzhang-ai-symbiotic-rail/visual/index.html"
  }
];
