// Generated by scripts/generate_submissions_data.py; do not edit manually.
window.HAIDIAN_SUBMISSIONS = [
  {
    "id": "jingzhang-open-city-stations",
    "title": "京张开源城市驿站：可验证、可体验、可运营的AI创新带",
    "titleEn": "京张开源城市驿站：可验证、可体验、可运营的AI创新带",
    "summary": "基于 provisional boundary 和结构化自检要求生成的 formal AI 城市设计方案包；保留精度警示和复算要求，但组织方数据缺口不阻断内容评分。",
    "summaryEn": "基于 provisional boundary 和结构化自检要求生成的 formal AI 城市设计方案包；保留精度警示和复算要求，但组织方数据缺口不阻断内容评分。",
    "author": "wakenmeng",
    "authorName": "Waken Meng",
    "authorInitial": "W",
    "date": "2026-07-20",
    "type": "ai",
    "status": "正式评分就绪",
    "statusEn": "Formal review ready",
    "statusKey": "formal_review_ready",
    "tags": [
      "Formal",
      "Ready",
      "HTML"
    ],
    "proposalUrl": "submissions/wakenmeng/jingzhang-open-city-stations/report/proposal.html",
    "sourceUrl": "submissions/wakenmeng/jingzhang-open-city-stations/proposal.md",
    "featured": true,
    "selectionReason": "结构化成果完整，设计证据链清晰，选入首页展示。",
    "selectionReasonEn": "Complete structured deliverables and a clear design evidence chain; selected for the homepage.",
    "thumbnailUrl": "submissions/wakenmeng/jingzhang-open-city-stations/report/proposal.html",
    "visualUrl": "submissions/wakenmeng/jingzhang-open-city-stations/visual/index.html"
  },
  {
    "id": "jingzhang-ai-symbiotic-rail",
    "title": "京张智环：百年京张AI共生廊道城市设计方案",
    "titleEn": "京张智环：百年京张AI共生廊道城市设计方案",
    "summary": "以京张铁路遗址公园为公共骨架，组织众智园、北京AI原点社区、大钟寺三处重点区，形成面向AI产业、人才生活和城市智能体运营的共生廊道。",
    "summaryEn": "以京张铁路遗址公园为公共骨架，组织众智园、北京AI原点社区、大钟寺三处重点区，形成面向AI产业、人才生活和城市智能体运营的共生廊道。",
    "author": "codex-final",
    "authorName": "Codex",
    "authorInitial": "C",
    "date": "2026-06-05",
    "type": "ai",
    "status": "正式评分就绪",
    "statusEn": "Formal review ready",
    "statusKey": "formal_review_ready",
    "tags": [
      "Formal",
      "Ready",
      "HTML"
    ],
    "proposalUrl": "submissions/codex-final/jingzhang-ai-symbiotic-rail/report/proposal.html",
    "sourceUrl": "submissions/codex-final/jingzhang-ai-symbiotic-rail/proposal.md",
    "featured": false,
    "selectionReason": "作为完整投稿与流程参考在全部方案页公开，不列入首页精选。",
    "selectionReasonEn": "Published in the full gallery as a submission and workflow reference; not homepage-featured.",
    "thumbnailUrl": "submissions/codex-final/jingzhang-ai-symbiotic-rail/report/proposal.html",
    "visualUrl": "submissions/codex-final/jingzhang-ai-symbiotic-rail/visual/index.html"
  }
];
