#!/usr/bin/env python3
"""Generate static frontend data for the public source registry.

This script reads ``data/source_registry.json``, produces a compact summary,
and writes it as a JavaScript module to ``source-registry-data.js`` for use
by the public website.

The generated file exports ``window.HAIDIAN_SOURCE_REGISTRY`` with the
following shape:

```js
window.HAIDIAN_SOURCE_REGISTRY = {
  "updatedDate": "YYYY-MM-DD",
  "registryPath": "data/source_registry.json",
  "counts": { "total": N, "by_review_status": {...}, ... },
  "usageRule": "...",
  "formal": [...],       // up to 20 approved formal-ready sources
  "background": [...],   // up to 20 background-only sources
  "provisional": [...],  // up to 20 provisional-only sources
  "needsReview": [...]   // up to 20 sources awaiting review
};
```

Do not edit the generated file manually. Re-run this script after updating
``data/source_registry.json``.

Usage
-----
Generate or update the data file::

    python3 scripts/generate_source_registry_data.py

Write to a custom output path::

    python3 scripts/generate_source_registry_data.py --out path/to/output.js

Check whether the generated file is current without writing::

    python3 scripts/generate_source_registry_data.py --check

Exit code is 0 on success and 1 when ``--check`` finds the file missing or
stale.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

from source_registry_utils import load_source_registry, summarize_source_registry


DEFAULT_OUTPUT = "source-registry-data.js"


def build_frontend_data(repo_root: Path) -> dict[str, Any]:
    registry = load_source_registry(repo_root)
    summary = summarize_source_registry(registry, limit=20)
    return {
        "updatedDate": summary.get("updated_date"),
        "registryPath": summary.get("registry_path"),
        "counts": summary.get("counts"),
        "usageRule": summary.get("usage_rule"),
        "formal": summary.get("approved_formal_sources", []),
        "background": summary.get("background_sources", []),
        "provisional": summary.get("provisional_sources", []),
        "needsReview": summary.get("needs_review_sources", []),
    }


def render_js(data: dict[str, Any]) -> str:
    return (
        "// Generated by scripts/generate_source_registry_data.py; do not edit manually.\n"
        "window.HAIDIAN_SOURCE_REGISTRY = "
        + json.dumps(data, ensure_ascii=False, indent=2)
        + ";\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--repo-root",
        default=".",
        help="Repository root directory (default: current working directory)",
    )
    parser.add_argument(
        "--out",
        default=DEFAULT_OUTPUT,
        help=f"Output path relative to --repo-root (default: {DEFAULT_OUTPUT})",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify the generated file is current without writing it",
    )
    args = parser.parse_args()

    repo_root = Path(args.repo_root).resolve()
    out_path = Path(args.out)
    if not out_path.is_absolute():
        out_path = repo_root / out_path
    content = render_js(build_frontend_data(repo_root))
    if args.check:
        if not out_path.exists():
            print(f"{out_path}: missing generated source registry data", file=sys.stderr)
            return 1
        current = out_path.read_text(encoding="utf-8")
        if current != content:
            print(f"{out_path}: generated data is stale; run scripts/generate_source_registry_data.py", file=sys.stderr)
            return 1
        return 0
    out_path.write_text(content, encoding="utf-8")
    print(out_path.relative_to(repo_root) if out_path.is_relative_to(repo_root) else out_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
