#!/usr/bin/env python3
"""Generate static frontend data for the public source registry."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

from source_registry_utils import load_source_registry, summarize_source_registry


DEFAULT_OUTPUT = "source-registry-data.js"


def build_frontend_data(repo_root: Path) -> dict[str, Any]:
    registry = load_source_registry(repo_root)
    summary = summarize_source_registry(registry, limit=20)
    return {
        "updatedDate": summary.get("updated_date"),
        "registryPath": summary.get("registry_path"),
        "counts": summary.get("counts"),
        "usageRule": summary.get("usage_rule"),
        "formal": summary.get("approved_formal_sources", []),
        "background": summary.get("background_sources", []),
        "provisional": summary.get("provisional_sources", []),
        "needsReview": summary.get("needs_review_sources", []),
    }


def render_js(data: dict[str, Any]) -> str:
    return (
        "// Generated by scripts/generate_source_registry_data.py; do not edit manually.\n"
        "window.HAIDIAN_SOURCE_REGISTRY = "
        + json.dumps(data, ensure_ascii=False, indent=2)
        + ";\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", default=".")
    parser.add_argument("--out", default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    repo_root = Path(args.repo_root).resolve()
    out_path = Path(args.out)
    if not out_path.is_absolute():
        out_path = repo_root / out_path
    content = render_js(build_frontend_data(repo_root))
    if args.check:
        if not out_path.exists():
            print(f"{out_path}: missing generated source registry data", file=sys.stderr)
            return 1
        current = out_path.read_text(encoding="utf-8")
        if current != content:
            print(f"{out_path}: generated data is stale; run scripts/generate_source_registry_data.py", file=sys.stderr)
            return 1
        return 0
    out_path.write_text(content, encoding="utf-8")
    print(out_path.relative_to(repo_root) if out_path.is_relative_to(repo_root) else out_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
