#!/usr/bin/env python3
"""Render a structured proposal exhibit as a single static HTML file.

This is a maintainer-only rendering tool. It takes a ``proposal.md`` and an
``exhibit.json`` (generated by ``generate_exhibit.py``) and produces a
self-contained static HTML exhibit page.

The output page is deterministic and dependency-free at render time. It
embeds no external resources; all figures are referenced via relative paths
inside the submission directory.

Supported module types
----------------------
- ``executive_summary`` — prose summary section
- ``concept_cards`` — grid of named concept cards with descriptions
- ``spatial_strategy`` — image + bullet-point strategy section
- ``agent_workflow`` — numbered workflow step list
- ``scenario_gallery`` — AI scenario cards with images
- ``timeline`` — phased implementation timeline
- ``metrics`` — key indicator table
- ``risk_notes`` — risk and compliance notes
- ``references`` — bibliography entries

Usage
-----
Render an exhibit page::

    python3 scripts/render_exhibit.py \
        submissions/<login>/<slug>/proposal.md \
        submissions/<login>/<slug>/exhibit.json \
        submissions/<login>/<slug>/exhibit.html

The script exits 0 on success and 1 on any rendering error.  The output file
is not committed to the repository (gitignored under ``submissions/``); it is
regenerated deterministically from the merged package.
"""

from __future__ import annotations

import argparse
import html
import json
import re
from pathlib import Path, PurePosixPath
from typing import Any

from validate_submission import load_track_registry, parse_front_matter, parse_track_metadata


ALLOWED_ASSET_EXTENSIONS = {".png", ".jpg", ".jpeg", ".webp", ".gif"}
ALLOWED_MODULE_TYPES = {
    "executive_summary",
    "concept_cards",
    "spatial_strategy",
    "agent_workflow",
    "scenario_gallery",
    "timeline",
    "metrics",
    "risk_notes",
    "references",
}

MODULE_LABELS = {
    "executive_summary": "方案摘要",
    "concept_cards": "核心概念",
    "spatial_strategy": "空间策略",
    "agent_workflow": "Agent 工作流",
    "scenario_gallery": "创新场景",
    "timeline": "落地路径",
    "metrics": "指标体系",
    "risk_notes": "风险与合规",
    "references": "参考资料",
}


class ExhibitError(ValueError):
    """Raised when exhibit input cannot be rendered safely."""


def text(value: Any, default: str = "") -> str:
    if value is None:
        return default
    return str(value)


def esc(value: Any) -> str:
    return html.escape(text(value), quote=True)


def safe_asset_path(raw_path: Any) -> str:
    value = text(raw_path).strip().replace("\\", "/")
    path = PurePosixPath(value)
    if not value:
        raise ExhibitError("asset path is empty")
    if "://" in value or value.startswith("//"):
        raise ExhibitError(f"external asset URLs are not allowed: {value}")
    if path.is_absolute() or ".." in path.parts:
        raise ExhibitError(f"unsafe asset path: {value}")
    if len(path.parts) < 2 or path.parts[0] != "assets":
        raise ExhibitError(f"asset path must start with assets/: {value}")
    if Path(path.name).suffix.lower() not in ALLOWED_ASSET_EXTENSIONS:
        allowed = ", ".join(sorted(ALLOWED_ASSET_EXTENSIONS))
        raise ExhibitError(f"asset path must use one of {allowed}: {value}")
    return path.as_posix()


def load_exhibit(path: Path) -> dict[str, Any]:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ExhibitError(f"{path}: invalid JSON: {exc}") from exc
    if not isinstance(data, dict):
        raise ExhibitError("exhibit.json must be a JSON object")
    if data.get("version") != 1:
        raise ExhibitError("exhibit.json version must be 1")
    modules = data.get("modules", [])
    if not isinstance(modules, list):
        raise ExhibitError("exhibit.json modules must be an array")
    for module in modules:
        if not isinstance(module, dict):
            raise ExhibitError("each exhibit module must be an object")
        module_type = module.get("type")
        if module_type not in ALLOWED_MODULE_TYPES:
            raise ExhibitError(f"unsupported module type: {module_type}")
    return data


def extract_sections(markdown: str) -> dict[str, str]:
    sections: dict[str, list[str]] = {}
    current: str | None = None
    for line in markdown.splitlines():
        match = re.match(r"^##\s+(.+?)\s*$", line)
        if match:
            current = match.group(1).strip()
            sections[current] = []
            continue
        if current:
            sections[current].append(line)
    return {key: "\n".join(value).strip() for key, value in sections.items()}


def first_section(sections: dict[str, str], label: str) -> str:
    for key, value in sections.items():
        if label in key:
            return value
    return ""


def lines_from_markdown_list(value: str) -> list[str]:
    items = []
    for line in value.splitlines():
        stripped = line.strip()
        if stripped.startswith("- "):
            items.append(stripped[2:].strip())
    return items


def slug(index: int, title: str) -> str:
    cleaned = re.sub(r"[^a-zA-Z0-9]+", "-", title).strip("-").lower()
    return f"m{index + 1}-{cleaned or 'section'}"


def paragraphs(value: Any) -> str:
    chunks = [chunk.strip() for chunk in text(value).split("\n\n") if chunk.strip()]
    if not chunks:
        return ""
    return "\n".join(f"<p>{esc(chunk)}</p>" for chunk in chunks)


def flush_paragraph(html_parts: list[str], paragraph_lines: list[str]) -> None:
    if not paragraph_lines:
        return
    html_parts.append(f"<p>{esc(' '.join(paragraph_lines))}</p>")
    paragraph_lines.clear()


def flush_list(html_parts: list[str], list_items: list[str]) -> None:
    if not list_items:
        return
    html_parts.append("<ul>" + "".join(f"<li>{esc(item)}</li>" for item in list_items) + "</ul>")
    list_items.clear()


def render_markdown_body(markdown: str) -> str:
    html_parts: list[str] = []
    paragraph_lines: list[str] = []
    list_items: list[str] = []

    for raw_line in markdown.splitlines():
        line = raw_line.strip()
        if not line:
            flush_paragraph(html_parts, paragraph_lines)
            flush_list(html_parts, list_items)
            continue

        heading = re.match(r"^(#{1,4})\s+(.+?)\s*$", line)
        if heading:
            flush_paragraph(html_parts, paragraph_lines)
            flush_list(html_parts, list_items)
            level = min(len(heading.group(1)) + 1, 4)
            if level == 2:
                level = 3
            html_parts.append(f"<h{level}>{esc(heading.group(2))}</h{level}>")
            continue

        list_item = re.match(r"^[-*]\s+(.+?)\s*$", line)
        if list_item:
            flush_paragraph(html_parts, paragraph_lines)
            list_items.append(list_item.group(1))
            continue

        flush_list(html_parts, list_items)
        paragraph_lines.append(line)

    flush_paragraph(html_parts, paragraph_lines)
    flush_list(html_parts, list_items)
    return "\n".join(html_parts)


def bullet_list(items: Any) -> str:
    if not isinstance(items, list) or not items:
        return ""
    return "<ul>" + "".join(f"<li>{esc(item)}</li>" for item in items) + "</ul>"


def image_figure(raw_path: Any, caption: Any = "") -> str:
    if not raw_path:
        return ""
    path = safe_asset_path(raw_path)
    caption_html = f"<figcaption>{esc(caption)}</figcaption>" if text(caption).strip() else ""
    return (
        '<figure class="media-frame">'
        f'<img src="{esc(path)}" alt="{esc(caption or "proposal exhibit image")}" loading="lazy">'
        f"{caption_html}</figure>"
    )


def module_title(module: dict[str, Any]) -> str:
    return text(module.get("title"), MODULE_LABELS.get(text(module.get("type")), "展示模块"))


def render_executive_summary(module: dict[str, Any], sections: dict[str, str]) -> str:
    body = text(module.get("body")) or first_section(sections, "摘要")
    return f'<div class="prose">{paragraphs(body)}</div>'


def render_concept_cards(module: dict[str, Any]) -> str:
    cards = module.get("cards")
    if not isinstance(cards, list):
        return ""
    html_parts = ['<div class="concept-grid">']
    for card in cards:
        if not isinstance(card, dict):
            continue
        html_parts.append(
            '<article class="concept-card">'
            f'<h3>{esc(card.get("title"))}</h3>'
            f'{paragraphs(card.get("body"))}'
            "</article>"
        )
    html_parts.append("</div>")
    return "".join(html_parts)


def render_spatial_strategy(module: dict[str, Any]) -> str:
    body = paragraphs(module.get("body"))
    items = bullet_list(module.get("items"))
    figure = image_figure(module.get("image"), module.get("caption"))
    return f'<div class="split-panel"><div class="prose">{body}{items}</div>{figure}</div>'


def render_agent_workflow(module: dict[str, Any]) -> str:
    steps = module.get("steps")
    if not isinstance(steps, list):
        return ""
    html_parts = ['<ol class="workflow">']
    for step in steps:
        if not isinstance(step, dict):
            continue
        html_parts.append(
            "<li>"
            f'<span class="step-name">{esc(step.get("name"))}</span>'
            f'{paragraphs(step.get("body"))}'
            "</li>"
        )
    html_parts.append("</ol>")
    return "".join(html_parts)


def render_scenario_gallery(module: dict[str, Any]) -> str:
    scenarios = module.get("scenarios")
    if not isinstance(scenarios, list):
        return ""
    html_parts = ['<div class="scenario-grid">']
    for scenario in scenarios:
        if not isinstance(scenario, dict):
            continue
        html_parts.append('<article class="scenario-card">')
        html_parts.append(image_figure(scenario.get("image"), scenario.get("caption")))
        html_parts.append(f'<h3>{esc(scenario.get("title"))}</h3>')
        html_parts.append(paragraphs(scenario.get("body")))
        html_parts.append("</article>")
    html_parts.append("</div>")
    return "".join(html_parts)


def render_timeline(module: dict[str, Any]) -> str:
    items = module.get("items")
    if not isinstance(items, list):
        return ""
    html_parts = ['<div class="timeline">']
    for item in items:
        if not isinstance(item, dict):
            continue
        html_parts.append(
            '<article class="timeline-item">'
            f'<span>{esc(item.get("period"))}</span>'
            f'<h3>{esc(item.get("title"))}</h3>'
            f'{paragraphs(item.get("body"))}'
            "</article>"
        )
    html_parts.append("</div>")
    return "".join(html_parts)


def render_metrics(module: dict[str, Any]) -> str:
    metrics = module.get("metrics")
    if not isinstance(metrics, list):
        return ""
    html_parts = ['<div class="metric-grid">']
    for metric in metrics:
        if not isinstance(metric, dict):
            continue
        html_parts.append(
            '<article class="metric-card">'
            f'<strong>{esc(metric.get("value"))}</strong>'
            f'<span>{esc(metric.get("label"))}</span>'
            f'<p>{esc(metric.get("note"))}</p>'
            "</article>"
        )
    html_parts.append("</div>")
    return "".join(html_parts)


def render_risk_notes(module: dict[str, Any], sections: dict[str, str]) -> str:
    items = module.get("items")
    if isinstance(items, list) and items:
        return bullet_list(items)
    return f'<div class="prose">{paragraphs(first_section(sections, "风险与合规说明"))}</div>'


def render_references(module: dict[str, Any], sections: dict[str, str]) -> str:
    items = module.get("items")
    if isinstance(items, list) and items:
        return bullet_list(items)
    section_items = lines_from_markdown_list(first_section(sections, "参考资料"))
    return bullet_list(section_items)


def render_module_body(module: dict[str, Any], sections: dict[str, str]) -> str:
    module_type = text(module.get("type"))
    if module_type == "executive_summary":
        return render_executive_summary(module, sections)
    if module_type == "concept_cards":
        return render_concept_cards(module)
    if module_type == "spatial_strategy":
        return render_spatial_strategy(module)
    if module_type == "agent_workflow":
        return render_agent_workflow(module)
    if module_type == "scenario_gallery":
        return render_scenario_gallery(module)
    if module_type == "timeline":
        return render_timeline(module)
    if module_type == "metrics":
        return render_metrics(module)
    if module_type == "risk_notes":
        return render_risk_notes(module, sections)
    if module_type == "references":
        return render_references(module, sections)
    raise ExhibitError(f"unsupported module type: {module_type}")


def render_html(proposal_path: Path, exhibit_path: Path) -> str:
    proposal_text = proposal_path.read_text(encoding="utf-8")
    metadata, body = parse_front_matter(proposal_text)
    exhibit = load_exhibit(exhibit_path)
    sections = extract_sections(body)

    title = metadata.get("title") or "方案展示"
    summary = metadata.get("summary") or first_section(sections, "摘要")
    author = metadata.get("author_github") or "unknown"
    license_value = metadata.get("license") or "CC-BY-4.0"
    language = metadata.get("language") or "zh"
    hero = exhibit.get("hero") if isinstance(exhibit.get("hero"), dict) else {}
    card = exhibit.get("card") if isinstance(exhibit.get("card"), dict) else {}
    badges = exhibit.get("badges") if isinstance(exhibit.get("badges"), list) else []
    modules = exhibit.get("modules", [])
    track_registry = load_track_registry(Path.cwd())
    track_ids = parse_track_metadata(card.get("tracks")) or parse_track_metadata(metadata.get("tracks"))
    track_badges = [
        text(track_registry.get(track_id, {}).get("title"), track_id)
        for track_id in track_ids[:3]
    ]

    nav_links = []
    module_sections = []
    for index, module in enumerate(modules):
        title_text = module_title(module)
        anchor = slug(index, title_text)
        nav_links.append(f'<a href="#{esc(anchor)}">{esc(title_text)}</a>')
        module_sections.append(
            f'<section class="module" id="{esc(anchor)}">'
            f'<div class="module-kicker">{esc(MODULE_LABELS.get(text(module.get("type")), "展示模块"))}</div>'
            f"<h2>{esc(title_text)}</h2>"
            f"{render_module_body(module, sections)}"
            "</section>"
        )
    nav_links.append('<a href="#full-proposal">完整方案</a>')
    full_proposal = (
        '<section class="module full-proposal" id="full-proposal">'
        '<div class="module-kicker">Proposal.md</div>'
        "<h2>完整方案正文</h2>"
        f'<article class="proposal-document">{render_markdown_body(body)}</article>'
        "</section>"
    )

    combined_badges = list(dict.fromkeys([*track_badges, *[text(item) for item in badges]]))[:8]
    badge_html = "".join(f"<span>{esc(item)}</span>" for item in combined_badges)
    hero_figure = image_figure(hero.get("image"), hero.get("caption"))
    hero_eyebrow = text(hero.get("eyebrow"), "AI 城市方案展示")
    hero_tagline = text(hero.get("tagline"), summary)

    return f"""<!doctype html>
<html lang="{esc(language)}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{esc(title)} | 百年京张 AI 创新带</title>
  <style>
    :root {{
      color-scheme: light;
      --paper: #f8f8f5;
      --ink: #202322;
      --muted: #5d6660;
      --line: #d8ddd5;
      --panel: #ffffff;
      --teal: #0e6f6b;
      --blue: #295f9f;
      --gold: #c28b1d;
      --red: #b64a3a;
    }}
    * {{ box-sizing: border-box; }}
    body {{
      margin: 0;
      background: var(--paper);
      color: var(--ink);
      font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      line-height: 1.65;
    }}
    a {{ color: inherit; }}
    .hero {{
      min-height: 82vh;
      display: grid;
      grid-template-columns: minmax(0, 0.95fr) minmax(320px, 1.05fr);
      gap: 40px;
      align-items: center;
      padding: 56px clamp(20px, 5vw, 72px) 40px;
      border-bottom: 1px solid var(--line);
    }}
    .eyebrow {{
      color: var(--teal);
      font-size: 0.82rem;
      font-weight: 800;
      letter-spacing: 0;
      margin-bottom: 16px;
    }}
    h1 {{
      max-width: 820px;
      margin: 0;
      font-size: clamp(2.4rem, 6vw, 6.3rem);
      line-height: 0.98;
      letter-spacing: 0;
    }}
    .tagline {{
      max-width: 760px;
      margin: 24px 0 0;
      color: #37403b;
      font-size: clamp(1.05rem, 2vw, 1.35rem);
    }}
    .summary {{
      max-width: 780px;
      margin: 20px 0 0;
      color: var(--muted);
      font-size: 1rem;
    }}
    .meta {{
      display: flex;
      flex-wrap: wrap;
      gap: 10px;
      margin-top: 28px;
      color: #34433e;
      font-size: 0.92rem;
    }}
    .meta span,
    .badges span {{
      border: 1px solid var(--line);
      background: rgba(255,255,255,0.72);
      border-radius: 999px;
      padding: 6px 12px;
    }}
    .badges {{
      display: flex;
      flex-wrap: wrap;
      gap: 10px;
      margin-top: 18px;
    }}
    .media-frame {{
      margin: 0;
      border: 1px solid var(--line);
      border-radius: 8px;
      overflow: hidden;
      background: var(--panel);
    }}
    .media-frame img {{
      display: block;
      width: 100%;
      aspect-ratio: 16 / 10;
      object-fit: cover;
    }}
    figcaption {{
      padding: 10px 12px;
      color: var(--muted);
      font-size: 0.86rem;
      border-top: 1px solid var(--line);
    }}
    .layout {{
      display: grid;
      grid-template-columns: 240px minmax(0, 1fr);
      gap: 36px;
      max-width: 1280px;
      margin: 0 auto;
      padding: 36px clamp(20px, 4vw, 48px) 64px;
    }}
    nav {{
      position: sticky;
      top: 16px;
      align-self: start;
      display: grid;
      gap: 8px;
      font-size: 0.94rem;
    }}
    nav a {{
      text-decoration: none;
      color: #43504a;
      padding: 8px 0;
      border-bottom: 1px solid var(--line);
    }}
    nav a:hover {{ color: var(--teal); }}
    .content {{
      display: grid;
      gap: 18px;
    }}
    .module {{
      background: var(--panel);
      border: 1px solid var(--line);
      border-radius: 8px;
      padding: clamp(20px, 4vw, 36px);
    }}
    .module-kicker {{
      color: var(--blue);
      font-size: 0.78rem;
      font-weight: 800;
      margin-bottom: 8px;
    }}
    h2 {{
      margin: 0 0 18px;
      font-size: clamp(1.45rem, 3vw, 2.4rem);
      line-height: 1.18;
      letter-spacing: 0;
    }}
    h3 {{
      margin: 0 0 8px;
      font-size: 1.05rem;
      line-height: 1.28;
    }}
    .proposal-document {{
      max-width: 820px;
    }}
    .proposal-document h3 {{
      margin-top: 30px;
      padding-top: 22px;
      border-top: 1px solid var(--line);
      color: #1f3935;
      font-size: clamp(1.2rem, 2vw, 1.65rem);
    }}
    .proposal-document h4 {{
      margin: 22px 0 10px;
      color: #26322e;
      font-size: 1.08rem;
    }}
    .proposal-document p {{
      color: #33403b;
    }}
    .full-proposal {{
      background: #fffdf7;
    }}
    p {{ margin: 0 0 12px; }}
    ul {{
      margin: 0;
      padding-left: 1.2rem;
    }}
    li + li {{ margin-top: 8px; }}
    .concept-grid,
    .scenario-grid,
    .metric-grid {{
      display: grid;
      grid-template-columns: repeat(2, minmax(0, 1fr));
      gap: 14px;
    }}
    .concept-card,
    .scenario-card,
    .metric-card,
    .timeline-item {{
      border: 1px solid var(--line);
      border-radius: 8px;
      padding: 18px;
      background: #fbfcfa;
    }}
    .concept-card:nth-child(3n + 1) {{ border-top: 4px solid var(--teal); }}
    .concept-card:nth-child(3n + 2) {{ border-top: 4px solid var(--gold); }}
    .concept-card:nth-child(3n + 3) {{ border-top: 4px solid var(--red); }}
    .split-panel {{
      display: grid;
      grid-template-columns: minmax(0, 0.88fr) minmax(280px, 1.12fr);
      gap: 24px;
      align-items: start;
    }}
    .workflow {{
      counter-reset: workflow;
      list-style: none;
      padding: 0;
      margin: 0;
      display: grid;
      gap: 12px;
    }}
    .workflow li {{
      counter-increment: workflow;
      border-left: 4px solid var(--teal);
      background: #f6faf8;
      padding: 14px 18px;
    }}
    .workflow li::before {{
      content: counter(workflow, decimal-leading-zero);
      color: var(--teal);
      font-weight: 800;
      margin-right: 10px;
    }}
    .step-name {{
      font-weight: 800;
    }}
    .scenario-card .media-frame {{
      margin-bottom: 14px;
    }}
    .timeline {{
      display: grid;
      gap: 12px;
    }}
    .timeline-item span {{
      display: inline-block;
      color: var(--red);
      font-weight: 800;
      margin-bottom: 8px;
    }}
    .metric-card strong {{
      display: block;
      color: var(--teal);
      font-size: clamp(2rem, 5vw, 3.2rem);
      line-height: 1;
      margin-bottom: 8px;
    }}
    .metric-card span {{
      display: block;
      font-weight: 800;
      margin-bottom: 8px;
    }}
    footer {{
      border-top: 1px solid var(--line);
      color: var(--muted);
      padding: 24px clamp(20px, 5vw, 72px);
      font-size: 0.9rem;
    }}
    @media (max-width: 860px) {{
      .hero,
      .layout,
      .split-panel {{
        grid-template-columns: 1fr;
      }}
      .hero {{
        min-height: auto;
        padding-top: 34px;
      }}
      nav {{
        position: static;
        grid-template-columns: repeat(2, minmax(0, 1fr));
      }}
      .concept-grid,
      .scenario-grid,
      .metric-grid {{
        grid-template-columns: 1fr;
      }}
    }}
  </style>
</head>
<body>
  <header class="hero">
    <div>
      <div class="eyebrow">{esc(hero_eyebrow)}</div>
      <h1>{esc(title)}</h1>
      <p class="tagline">{esc(hero_tagline)}</p>
      <p class="summary">{esc(summary)}</p>
      <div class="meta">
        <span>作者：{esc(author)}</span>
        <span>语言：{esc(language)}</span>
        <span>许可：{esc(license_value)}</span>
      </div>
      <div class="badges">{badge_html}</div>
    </div>
    {hero_figure}
  </header>
  <main class="layout">
    <nav aria-label="方案模块导航">
      {"".join(nav_links)}
    </nav>
    <div class="content">
      {"".join(module_sections)}
      {full_proposal}
    </div>
  </main>
  <footer>
    本页面由结构化 proposal.md 与 exhibit.json 生成，不包含用户提交脚本。涉及空间、交通、建设强度和政策判断的内容均需人工复核。
  </footer>
</body>
</html>
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("proposal", type=Path)
    parser.add_argument("exhibit", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    try:
        rendered = render_html(args.proposal, args.exhibit)
    except ExhibitError as exc:
        parser.error(str(exc))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
