#!/usr/bin/env python3
"""Rebuild the A3 booklet and A0 boards (zh + en) for jingzhang-platform.

Every page is rendered from the same canonical sources as the figures and
metrics: geometry/*.geojson -> tools/recompute_metrics.py -> metrics.json,
and assets/figures/*.png (generated by tools/generate_figures.py). No third-
party images, fonts, logos, or remote resources are embedded. Text content
mirrors proposal.md / proposal.en.md.

Rendering uses headless Google Chrome (--print-to-pdf); the generated PDFs
must be re-run whenever geometry, metrics, or figures change.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CHROME = (
    "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
    if sys.platform == "darwin"
    else "google-chrome"
)

# ---------- metrics ----------
M = json.load(open(ROOT / "metrics.json", encoding="utf-8"))["metrics"]

KEY_AREAS = [  # (name_zh, name_en, announced_ha, computed_ha)
    ("众智园AI自主创新加速区", "Zhongzhiyuan AI Acceleration Area", 192.1, 192.9),
    ("北京AI原点社区", "Beijing AI Origin Community", 104.3, 104.3),
    ("大钟寺AI产业聚集区", "Dazhongsi AI Industry Cluster", 72.0, 72.0),
]

METRIC_LABELS = [
    ("site_area_sqm", "场地面积", "Site area", "sqm", "geometry/site_boundary.geojson", "high"),
    ("green_space_area_sqm", "绿地面积", "Green space area", "sqm", "geometry/green_space.geojson", "medium"),
    ("public_space_area_sqm", "公共空间面积", "Public space area", "sqm", "geometry/public_space.geojson", "medium"),
    ("green_ratio", "绿地率", "Green ratio", "ratio", "green_space_area_sqm / site_area_sqm", "medium"),
    ("public_space_ratio", "公共空间占比", "Public space ratio", "ratio", "public_space_area_sqm / site_area_sqm", "medium"),
    ("key_area_count", "重点片区数", "Key area count", "count", "geometry/key_areas.geojson", "high"),
    ("key_area_total_area_sqm", "重点片区合计面积", "Key area total area", "sqm", "geometry/key_areas.geojson", "medium"),
    ("land_use_block_count", "用地块数", "Land-use block count", "count", "geometry/land_use.geojson", "high"),
    ("building_footprint_area_sqm", "建筑基底面积", "Building footprint area", "sqm", "geometry/buildings.geojson", "medium"),
    ("building_count", "建筑栋数", "Building count", "count", "geometry/buildings.geojson", "medium"),
    ("road_network_length_m", "路网长度", "Road network length", "m", "geometry/roads.geojson", "medium"),
    ("phasing_area_sqm", "分期覆盖面积", "Phasing coverage area", "sqm", "geometry/phasing.geojson", "medium"),
]


def metric_value(key: str) -> float:
    return M[key]["value"]


def mfmt(key: str, digits: int = 1) -> str:
    v = metric_value(key)
    if key in ("green_ratio", "public_space_ratio"):
        return f"{v * 100:.2f}%"
    if key in ("road_network_length_m",):
        return f"{v / 1000:.1f} km"
    if key in ("site_area_sqm", "phasing_area_sqm", "key_area_total_area_sqm"):
        return f"{v / 1e6:.2f} km²"
    if key in ("green_space_area_sqm", "public_space_area_sqm", "building_footprint_area_sqm"):
        return f"{v / 1e4:.1f} ha"
    if v == int(v):
        return f"{int(v):,}"
    return f"{v:,.{digits}f}"


# ---------- shared text snippets (zh / en pairs) ----------
PROV_WARN_ZH = (
    "本页所有面积与比例均基于组织方临时几何（provisional_constraint）按 EPSG:4548 复算，"
    "官方边界发布后须以 tools/recompute_metrics.py 重算并重新出图。"
)
PROV_WARN_EN = (
    "All areas and ratios on this page are recomputed from the organizer's provisional "
    "geometry (provisional_constraint) in EPSG:4548; they must be recomputed by "
    "tools/recompute_metrics.py and redrawn when official polygons are published."
)
LICENSE_ZH = "许可：COMMUNITY-DISPLAY-ONLY（仅限竞赛评审展示；禁止商用）· 全部文字/图件/指标由方案自产，来源见 report/copyright_statement.md 与 sources.json"
LICENSE_EN = "License: COMMUNITY-DISPLAY-ONLY (competition review display only, no commercial use) · All text, figures, and metrics are self-produced; sources in report/copyright_statement.md and sources.json"

SCENARIOS_ZH = [
    ("01 开源发布厅", "北京AI原点社区·公共建筑首层/社区开放节点"),
    ("02 安全治理沙盒", "众智园·花园型街区开放节点"),
    ("03 端侧算力驿站", "总体设计范围·公共服务设施节点"),
    ("04 AI慢行导航", "京张遗址公园活力带·慢行廊道"),
    ("05 大钟寺国际路演客厅", "大钟寺·站城一体商业节点"),
    ("06 清河低碳创新廊", "众智园临清河界面·滨水蓝绿空间"),
    ("07 近校成果转化街", "北京AI原点社区·校区园区缝合段"),
    ("08 数据要素会客厅", "大钟寺·商业与轨道复合节点"),
    ("09 AI生活服务样板街", "社区与商业交汇处·小尺度街区"),
    ("10 全球AI活动周路线", "一带公共空间系统·联廊与广场节点"),
    ("11 月台共享候车亭", "三座月台广场与联廊节点·候车复合空间"),
    ("12 开源协作贡献墙", "AI原点社区与大钟寺路口象限·公共界面"),
]
SCENARIOS_EN = [
    ("01 Open-source release hall", "AI Origin Community · ground floor / community node"),
    ("02 Safety governance sandbox", "Zhongzhiyuan · garden-block open node"),
    ("03 Edge-compute service station", "Overall design area · public-service node"),
    ("04 AI slow-traffic navigation", "Jingzhang heritage-park vitality belt · corridor"),
    ("05 Dazhongsi international roadshow hall", "Dazhongsi · station-city commercial node"),
    ("06 Qinghe low-carbon innovation gallery", "Zhongzhiyuan Qinghe frontage · waterfront"),
    ("07 Campus-near transfer street", "AI Origin Community · campus-park seam"),
    ("08 Data-element salon", "Dazhongsi · commercial and rail composite node"),
    ("09 AI daily-life sample street", "Community-commerce junction · small block"),
    ("10 Global AI activity-week route", "Belt public-space system · gallery and square nodes"),
    ("11 Platform shared waiting pavilion", "Three platform squares and gallery nodes · hybrid waiting space"),
    ("12 Open-source collaboration wall", "AI Origin Community & Dazhongsi quadrant · public interface"),
]
PERSONAS_ZH = [
    ("老年人", "大字/语音导视、坐下即达、不用智能终端也能办事", "窗口、电话与上门线下等价服务"),
    ("儿童", "安全路径、家长可见活动、AI科普不采集儿童数据", "活动区人工值守、教育内容教师复核"),
    ("残障人士", "全通道无障碍、盲文/触觉地图、人工复核AI导航", "无障碍巡检月报公开、工单30天闭环"),
    ("低收入人群", "免费公共服务、廉价通勤休闲、就业技能机会", "收费AI服务保留免费基础档"),
    ("照护者", "宽通道、母婴/照护休息与协助点", "人工服务与呼叫响应公示"),
    ("非智能终端用户", "不装APP也能查询、预约、反馈", "公共终端/电话/窗口等效服务链"),
]
PERSONAS_EN = [
    ("Older adults", "Large-type/voice wayfinding, rest along routes, service without smart devices", "Offline window, phone, and home-visit equivalents"),
    ("Children", "Safe routes, parent-visible activities, no data collection in AI education", "Staffed activity zones, teacher-reviewed educational content"),
    ("People with disabilities", "Full-barrier-free routes, Braille/tactile maps, human-reviewed AI navigation", "Monthly accessibility inspection reports, 30-day work-order closure"),
    ("Low-income residents", "Free public services, affordable commuting and leisure, skills opportunities", "Free basic tier kept for paid AI services"),
    ("Caregivers", "Wide corridors, mother/care rest rooms and assistance points", "Staffed care points with published response times"),
    ("Non-smart-device users", "Query, booking, and feedback without an app", "Public terminals, phone, and window equivalent service chains"),
]
MECH_ZH = [
    ("线下等价服务", "每个AI场景配窗口、电话或人工柜台等效通道，数字服务只增强不替代"),
    ("公众参与渠道", "年度开放日、街区议事会与线上反馈并行，参与记录不用于商业画像"),
    ("算法申诉渠道", "对智能体建议/评分/调度可人工申诉，非算法人员复核并限期答复"),
    ("人工可访问性检查", "每年由第三方按无障碍规范人工检查公共空间与界面，报告公开"),
]
MECH_EN = [
    ("Offline equivalent services", "Every AI scenario keeps window, phone, or counter equivalents; digital enhances, never replaces"),
    ("Public participation channels", "Annual open days, block assemblies, and online feedback in parallel; records never used for commercial profiling"),
    ("Algorithm appeal channel", "Agent suggestions/scores/dispatch can be appealed; reviewed by non-algorithm staff with a deadline"),
    ("Manual accessibility inspection", "Annual third-party manual inspection of public space and interfaces; reports published"),
]
GOV_ZH = [
    ("数据治理", "数据来源、隐私边界与授权前置"),
    ("成熟度分级", "M0 概念 → M1 试点 → M2 运营"),
    ("试点周期", "6–24 个月，附第三方评估"),
    ("人工复核", "评测/内容/审计人工复核后发布"),
    ("退出机制", "安全事件、授权缺失、审计违规即停"),
    ("量化KPI", "概念指标，非承诺目标"),
]
GOV_EN = [
    ("Data governance", "Data sources, privacy boundaries, authorization first"),
    ("Maturity stages", "M0 concept → M1 pilot → M2 operation"),
    ("Pilot period", "6–24 months with third-party evaluation"),
    ("Human review", "Evaluation/content/audit released after human review"),
    ("Exit mechanism", "Stop on safety incident, missing authorization, or audit failure"),
    ("Quantitative KPIs", "Conceptual indicators, not committed targets"),
]
CHAIN_ZH = ["高校策源", "开源协作", "企业转化", "公共体验", "国际传播"]
CHAIN_EN = ["University seeding", "Open-source collaboration", "Enterprise conversion", "Public experience", "International communication"]
REGS_ZH = [
    ("北纬社区等北部创新社区", "承接中试放大与规模化研发外溢", "共享产业链招商图谱与人才服务网络"),
    ("未来科学城（昌平）", "前沿科学向产业转化的大科学装置协同", "创新链上下游分工：策源-中试-制造"),
    ("怀柔科学城", "大科学装置与基础研究成果策源联动", "高端人才交流与成果路演互访"),
    ("北京经开区（亦庄）", "智能终端与智造环节规模化转化", "场景开放与供应链协作、展会互认"),
    ("京津冀腹地", "制造、场景与数据要素腹地空间", "场景开放城市联盟与产业飞地协作（概念建议）"),
]
REGS_EN = [
    ("North-wei communities (Haidian north)", "Pilot scale-up and R&D spillover", "Shared industry-recruitment map and talent service network"),
    ("Future Science City (Changping)", "Large-facility coordination from frontier science to industry", "Seeding-pilot-manufacturing division of the innovation chain"),
    ("Huairou Science City", "Source-side seeding of large facilities and basic research", "Talent exchange and roadshow mutual visits"),
    ("Beijing E-Town (Yizhuang)", "Scaled conversion of smart devices and manufacturing", "Scenario opening, supply-chain collaboration, fair recognition"),
    ("Beijing-Tianjin-Hebei hinterland", "Manufacturing, scenario, and data-factor hinterland", "Scenario-open city alliance and industrial enclave (conceptual)"),
]
JZ_ZH = [
    ("JZ-01 京张遗址公园慢行断点缝合", "公共空间/交通", "道路红线、桥下空间、交通组织复核"),
    ("JZ-02 众智园清河创新界面", "蓝绿空间/产业展示", "河道蓝线、生态和防洪条件"),
    ("JZ-03 原点社区近校成果转化街", "城市更新/产业服务", "校区边界、权属、首层业态"),
    ("JZ-04 大钟寺站四象限步行连通", "轨道一体化/慢行", "轨道站点、道路交叉口、市政管线"),
    ("JZ-05 AI公共服务与端侧算力节点", "新基建/公共服务", "能源、算力、安全和运营主体"),
    ("JZ-06 全球AI活动周公共路线", "运营/品牌", "公共空间许可、活动安全、版权清权"),
]
JZ_EN = [
    ("JZ-01 Jingzhang heritage-park slow-traffic gap stitching", "Public space / transport", "Road redlines, underpass space, traffic review"),
    ("JZ-02 Zhongzhiyuan Qinghe innovation frontage", "Blue-green / industry display", "River blue line, ecology, flood conditions"),
    ("JZ-03 Origin community campus-near transfer street", "Urban renewal / industry service", "Campus boundary, ownership, ground-floor uses"),
    ("JZ-04 Dazhongsi station four-quadrant pedestrian link", "Rail integration / slow traffic", "Station, junctions, municipal utilities"),
    ("JZ-05 AI public service & edge-compute node", "New infrastructure / public service", "Energy, compute, safety, operator"),
    ("JZ-06 Global AI activity-week public route", "Operation / branding", "Public-space permit, event safety, rights clearance"),
]
OPS_ZH = [
    ("年度活动体系", "AI开发者节、场景开放日、竞赛路演、记忆体验月；年活动≥30场、年参与≥10万人次"),
    ("开发者社区", "开源协作营、贡献墙荣誉榜、技术夜谈；年贡献≥60项、志愿者≥300人"),
    ("场景开放机制", "每年发布场景清单、开放申报、公开评估；年开放≥10项、试点转化≥5项"),
    ("国际传播机制", "双语主题地图、活动周路线、国际路演季；年国际交流≥20场"),
]
OPS_EN = [
    ("Annual events", "AI developer festival, scenario open days, competition roadshows, memory experience month; ≥30 events/yr, ≥100k participants/yr"),
    ("Developer community", "Open-source camps, contribution-wall honor board, tech night talks; ≥60 projects/yr, ≥300 volunteers"),
    ("Scenario opening", "Annual scenario list, open application, public evaluation; ≥10 opened/yr, ≥5 pilots converted"),
    ("International communication", "Bilingual theme map, activity-week route, international roadshow season; ≥20 international exchanges/yr"),
]
COMP_ZH = [
    ("月台候车亭组件", "站台檐口意象+共享办公/快闪/休憩复合，模块化可拆装"),
    ("导视与里程石组件", "三级导视+里程石文化符号，中英双语、无障碍多模"),
    ("贡献墙组件", "数字化贡献展示+实体荣誉榜，可申请下线"),
    ("绿廊座椅与遮荫组件", "无障碍座椅带+遮荫乔木+照明分级"),
    ("无障碍坡道与触觉地图组件", "全通道无障碍+盲文触觉地图，巡检月报公开"),
    ("快闪与展陈组件", "可移动展架、路演台与灯光音响接口"),
]
COMP_EN = [
    ("Platform waiting-pavilion kit", "Platform-eave imagery + co-working/pop-up/rest hybrid, modular and demountable"),
    ("Wayfinding & milestone-stone kit", "Three-level wayfinding + heritage symbols, bilingual, multimodal accessible"),
    ("Contribution-wall kit", "Digital contribution display + physical honor board, opt-out available"),
    ("Gallery seat & shade kit", "Barrier-free seating strips + shade trees + tiered lighting"),
    ("Accessible ramp & tactile-map kit", "Full-route accessibility + Braille/tactile maps, monthly inspection reports"),
    ("Pop-up & exhibit kit", "Mobile display frames, roadshow stage, lighting/sound interfaces"),
]
SCEN_TEST_ZH = [
    ("T1 开放模型评测场", "众智园创新月台·园区平台节点", "自主模型能力/安全/标准符合性评测", "M2验证·12个月·第三方复核后发布"),
    ("T2 端侧AI城市服务沙盒", "总体设计范围服务节点", "端侧算力、智能导视、慢行感知现场试验", "M2验证·18个月·街道共建人工巡检"),
    ("T3 智能终端消费体验场", "大钟寺消费月台·商业公共空间", "智能终端、智能体、内容消费合规演示", "M2验证·12个月·商家平台联合运营"),
]
SCEN_TEST_EN = [
    ("T1 Open model evaluation field", "Zhongzhiyuan innovation platform", "Capability/safety/standards evaluation of models", "M2 validation · 12 mo · third-party review before release"),
    ("T2 Edge AI civic service sandbox", "Overall-area service node", "Edge compute, smart wayfinding, slow-traffic sensing trials", "M2 validation · 18 mo · street co-build with manual patrol"),
    ("T3 Smart-device consumption experience field", "Dazhongsi consumption platform", "Smart devices, agents, content-consumption compliance demos", "M2 validation · 12 mo · merchant-platform joint operation"),
]
ASSUMP_ZH = [
    ("A-CONTROLS-001", "法定控制线、红线、权属与工程条件待专业确认"),
    ("A-BOUNDARY-001", "场地与重点区为临时几何，官方边界发布后整体重算"),
    ("A-CASES-001", "全球案例机制不可移植，事实以公开来源为准"),
    ("A-SCENARIO-KPI-001", "场景与运营KPI为概念指标，非承诺目标"),
    ("A-OPERATION-001", "年度活动等运营机制需许可、安全报备与版权清权"),
    ("A-HERITAGE-001", "遗产符号与历史叙事待文保与权利方确认"),
    ("A-ACCESSIBILITY-001", "包容性机制为设计意图，实施时按规范验收"),
]
ASSUMP_EN = [
    ("A-CONTROLS-001", "Statutory controls, redlines, ownership, engineering conditions pending professional confirmation"),
    ("A-BOUNDARY-001", "Site and key areas are provisional geometry; full recompute when official polygons publish"),
    ("A-CASES-001", "Global cases are not transplantable; facts follow their public sources"),
    ("A-SCENARIO-KPI-001", "Scenario and operation KPIs are conceptual indicators, not commitments"),
    ("A-OPERATION-001", "Annual events and operation mechanisms need permits, safety filings, and rights clearance"),
    ("A-HERITAGE-001", "Heritage symbols and historical narratives pending authority and rights-holder confirmation"),
    ("A-ACCESSIBILITY-001", "Inclusivity mechanisms are design intent; verified against standards at implementation"),
]

# ---------- HTML helpers ----------
def chips(items, cls="chip") -> str:
    return "".join(f'<span class="{cls}">{a}<b>{b}</b></span>' if isinstance(b, str) else f'<span class="{cls}">{a}</span>' for a, b in items)


def fig_block(fig: str, caption_zh: str, caption_en: str) -> str:
    path = (ROOT / "assets" / "figures" / fig).as_uri()
    return (
        f'<figure><img src="{path}" alt="{caption_zh}">'
        f"<figcaption>{caption_zh} · {caption_en}</figcaption></figure>"
    )


def metric_rows() -> str:
    rows = ""
    for key, lzh, len_, unit, src, conf in METRIC_LABELS:
        v = metric_value(key)
        if key in ("green_ratio", "public_space_ratio"):
            disp = f"{v * 100:.4f} ({v * 100:.2f}%)"
        elif key == "road_network_length_m":
            disp = f"{v:,.1f} m ({v/1000:.1f} km)"
        elif key in ("site_area_sqm", "phasing_area_sqm", "key_area_total_area_sqm"):
            disp = f"{v:,.1f} m² ({v/1e6:.2f} km²)"
        elif key in ("green_space_area_sqm", "public_space_area_sqm", "building_footprint_area_sqm"):
            disp = f"{v:,.1f} m² ({v/1e4:.1f} ha)"
        else:
            disp = f"{v:,.1f}" if isinstance(v, float) else str(v)
        rows += (
            f"<tr><td>{lzh}</td><td>{len_}</td><td>{disp}</td>"
            f"<td>{src}</td><td>{conf}</td></tr>"
        )
    return rows


def page(title_zh, title_en, body_zh, body_en, fig_zh=None, fig_en=None, no=None, total=None):
    return {
        "t_zh": title_zh, "t_en": title_en,
        "b_zh": body_zh, "b_en": body_en,
        "f_zh": fig_zh, "f_en": fig_en, "no": no, "total": total,
    }


def esc(s: str) -> str:
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def build_booklet_pages():
    P = []
    # ---- P1 cover ----
    body = f"""
    <div class="cover">
      <div class="cover-kicker">百年京张AI创新带城市设计方案 · 2026 国际方案征集</div>
      <h1>京张月台 <span>JINGZHANG PLATFORM</span></h1>
      <p class="cover-sub">把百年站台变成AI时代开放平台——站台是等待、会合与出发的场所，平台是开源、开放与协作的场所。</p>
      <div class="cover-cards">
        <div class="c3card"><h4>世界级AI创新生态体系</h4><p>高校策源 → 开源协作 → 企业转化 → 公共体验 → 国际传播</p></div>
        <div class="c3card"><h4>适配AI新质生产力的新型城市形态</h4><p>一条联廊（约9公里绿道联廊）、三座月台、两股轨道</p></div>
        <div class="c3card"><h4>全球AI创新人才向往的高品质城区</h4><p>百年京张文化带 · 都市AI生活体验带 · AI融合创新带</p></div>
      </div>
      <div class="metric-strip">
        <span>场地 {mfmt('site_area_sqm')}</span><span>绿地率 {mfmt('green_ratio')}</span>
        <span>公共空间占比 {mfmt('public_space_ratio')}</span><span>重点片区 {mfmt('key_area_count')} 处</span>
        <span>重点片区合计 {mfmt('key_area_total_area_sqm')}</span>
      </div>
      <p class="cover-note">{PROV_WARN_ZH}</p>
    </div>"""
    body_en = f"""
    <div class="cover">
      <div class="cover-kicker">Urban Design Proposal, Centennial Jingzhang AI Innovation Belt · 2026 Open Call</div>
      <h1>JINGZHANG PLATFORM <span>京张月台</span></h1>
      <p class="cover-sub">Turning a centennial station platform into an open platform for the AI era — the station is a place to wait, meet, and depart; the platform is a place of open source, openness, and collaboration.</p>
      <div class="cover-cards">
        <div class="c3card"><h4>World-class AI innovation ecosystem</h4><p>University seeding → open-source collaboration → enterprise conversion → public experience → international communication</p></div>
        <div class="c3card"><h4>New urban form for AI productivity</h4><p>One gallery (≈9 km green corridor), three platforms, two tracks</p></div>
        <div class="c3card"><h4>A high-quality district for global AI talent</h4><p>Centennial Jingzhang culture belt · urban AI-life experience belt · AI-integrated innovation belt</p></div>
      </div>
      <div class="metric-strip">
        <span>Site {mfmt('site_area_sqm')}</span><span>Green ratio {mfmt('green_ratio')}</span>
        <span>Public space {mfmt('public_space_ratio')}</span><span>Key areas {mfmt('key_area_count')}</span>
        <span>Key area total {mfmt('key_area_total_area_sqm')}</span>
      </div>
      <p class="cover-note">{PROV_WARN_EN}</p>
    </div>"""
    P.append(page("封面", "Cover", body, body_en, no=1))

    # ---- P2 overview & three scopes ----
    scopes_zh = [
        ("统筹研究范围", "世界级AI创新生态体系的产业与未来城市研究"),
        ("总体设计范围", "控规深度城市设计：城市更新、交通市政与风貌"),
        ("重点区域范围", "三处重点片区详细设计（必选项）"),
    ]
    scopes_en = [
        ("Coordinated research area", "Industry and future-city research for a world-class AI ecosystem"),
        ("Overall design area", "Regulatory-plan-depth urban design: renewal, transport, character"),
        ("Key areas", "Detailed design of the three required key areas"),
    ]
    body = f"""
    <h3>一条联廊、三座月台、两股轨道</h3>
    <p>沿京张遗址公园的约9公里南北贯通绿道联廊是历史与公共空间主轴；三座月台对应三处重点区域；两股轨道对应中关村服务轨（西侧）与小月河场景轨（东侧）。</p>
    <div class="grid3">
      {"".join(f'<div class="c3card"><h4>{a}</h4><p>{b}</p></div>' for a, b in scopes_zh)}
    </div>
    {fig_block("site-overview.png", "总览地图：用地分区、交通慢行、蓝绿公共空间、建筑与更新项目、AI场景节点", "Overview map: land use, slow traffic, blue-green and public space, buildings and renewal, AI scenario nodes")}
    """
    body_en = f"""
    <h3>One gallery, three platforms, two tracks</h3>
    <p>The ≈9 km north-south green corridor along the Jingzhang heritage park is the spine of heritage and public life; the three platforms correspond to the key areas; the two tracks are the Zhongguancun service track (west) and the Xiaoyuehe scenario track (east).</p>
    <div class="grid3">
      {"".join(f'<div class="c3card"><h4>{a}</h4><p>{b}</p></div>' for a, b in scopes_en)}
    </div>
    {fig_block("site-overview.en.png", "Overview map: land use, slow traffic, blue-green and public space, buildings and renewal, AI scenario nodes", "总览地图：用地分区、交通慢行、蓝绿公共空间、建筑与更新项目、AI场景节点")}
    """
    P.append(page("总览与三层范围", "Overview & Three-Level Scope", body, body_en, no=2))

    # ---- P3 key areas ----
    ka_rows = "".join(
        f"<tr><td>{a}</td><td>{b}</td><td>{c:.1f} ha</td><td>{d:.1f} ha</td></tr>"
        for a, b, c, d in KEY_AREAS
    )
    body = f"""
    <p>三处重点片区详细设计为必选项。以下面积为公告约面积与临时几何复算面积对照；公告未给出四至，矩形边不得解释为地块或道路红线。</p>
    <table class="mt"><tr><th>重点片区</th><th>设计定位</th><th>公告约面积</th><th>复算面积(EPSG:4548)</th></tr>{ka_rows}
    <tr class="sum"><td colspan="2">合计（公告 368.4 ha / 复算 369.3 ha）</td><td>368.4 ha</td><td>{mfmt('key_area_total_area_sqm')}</td></tr></table>
    {fig_block("key-areas.png", "三处重点区域索引与设计任务图", "Three key areas index and design-task map")}
    """
    body_en = f"""
    <p>Detailed design of the three key areas is mandatory. Areas below compare the announced approximate values with recomputed values from the provisional geometry; the announcement gives no extents, so rectangle edges must not be read as plot or road redlines.</p>
    <table class="mt"><tr><th>Key area</th><th>Design position</th><th>Announced approx.</th><th>Recomputed (EPSG:4548)</th></tr>{ka_rows}
    <tr class="sum"><td colspan="2">Total (announced 368.4 ha / recomputed 369.3 ha)</td><td>368.4 ha</td><td>{mfmt('key_area_total_area_sqm')}</td></tr></table>
    {fig_block("key-areas.en.png", "Three key areas index and design-task map", "三处重点区域索引与设计任务图")}
    """
    P.append(page("重点区域", "Key Areas", body, body_en, no=3))

    # ---- P4 land use & phasing ----
    body = f"""
    <p>用地分类依据《国土空间调查、规划、用途管制用地用海分类指南（试行）》（自然资源部，2020）；控规深度按《城市、镇控制性详细规划编制审批办法》（住建部令第7号）组织。分期范围完整覆盖设计边界。</p>
    <div class="metric-strip">
      <span>用地块数 {mfmt('land_use_block_count')}</span><span>分期覆盖 {mfmt('phasing_area_sqm')}</span>
      <span>建筑基底 {mfmt('building_footprint_area_sqm')}</span><span>建筑 {mfmt('building_count')} 栋</span>
    </div>
    {fig_block("land-use-structure.png", "用地结构、分期与拆改留方案", "Land-use structure, phasing, and retain-renovate-demolish strategy")}
    """
    body_en = f"""
    <p>Land-use classification follows the Land-sea Classification Guide for National Territory Surveys, Planning and Use Control (MNR, 2020); regulatory-plan depth follows the Procedures for Formulation and Approval of Regulatory Detailed Plans (MOHURD Order No. 7). The phasing polygons fully cover the design boundary.</p>
    <div class="metric-strip">
      <span>Land-use blocks {mfmt('land_use_block_count')}</span><span>Phasing coverage {mfmt('phasing_area_sqm')}</span>
      <span>Building footprint {mfmt('building_footprint_area_sqm')}</span><span>Buildings {mfmt('building_count')}</span>
    </div>
    {fig_block("land-use-structure.en.png", "Land-use structure, phasing, and retain-renovate-demolish strategy", "用地结构、分期与拆改留方案")}
    """
    P.append(page("用地结构与分期", "Land Use & Phasing", body, body_en, no=4))

    # ---- P5 mobility & blue-green ----
    body = f"""
    <p>以京张遗址公园活力带为骨架统筹清河、小月河与慢行体系，识别慢行断点、上跨环路节点与南北端景观节点；围绕轨道站点一体化组织步行连通。</p>
    <div class="metric-strip">
      <span>路网长度 {mfmt('road_network_length_m')}</span><span>绿地 {mfmt('green_space_area_sqm')}（{mfmt('green_ratio')}）</span>
      <span>公共空间 {mfmt('public_space_area_sqm')}（{mfmt('public_space_ratio')}）</span>
    </div>
    {fig_block("mobility-bluegreen.png", "交通慢行与蓝绿公共空间：建筑、道路、绿地、公共空间", "Mobility, slow traffic, blue-green and public space: buildings, roads, green space, public space")}
    """
    body_en = f"""
    <p>The Jingzhang heritage-park vitality belt frames the Qinghe and Xiaoyuehe systems and slow traffic; gaps, overpass nodes, and north/south landscape nodes are identified, with station-integrated pedestrian links around rail stations.</p>
    <div class="metric-strip">
      <span>Road network {mfmt('road_network_length_m')}</span><span>Green {mfmt('green_space_area_sqm')} ({mfmt('green_ratio')})</span>
      <span>Public space {mfmt('public_space_area_sqm')} ({mfmt('public_space_ratio')})</span>
    </div>
    {fig_block("mobility-bluegreen.en.png", "Mobility, slow traffic, blue-green and public space: buildings, roads, green space, public space", "交通慢行与蓝绿公共空间：建筑、道路、绿地、公共空间")}
    """
    P.append(page("交通与蓝绿公共空间", "Mobility & Blue-Green Public Space", body, body_en, no=5))

    # ---- P6 ecosystem & scenarios ----
    body = f"""
    <h3>AI生态图谱（概念版）</h3>
    <p class="chain">{" → ".join(f"<b>{a}</b>" for a in CHAIN_ZH)}</p>
    <p>区域协同（概念建议）：</p>
    <table class="mt"><tr><th>协同板块</th><th>关系</th><th>协同机制</th></tr>
    {"".join(f"<tr><td>{a}</td><td>{b}</td><td>{c}</td></tr>" for a, b, c in REGS_ZH)}</table>
    <h3>12 场景卡 + 3 测试场景</h3>
    <div class="grid2">
      {"".join(f'<div class="scc"><b>{a}</b><p>{b}</p></div>' for a, b in SCENARIOS_ZH)}
    </div>
    <div class="metric-strip">
      {"".join(f"<span>{a} · {b}</span>" for a, b, c, d in SCEN_TEST_ZH)}
    </div>
    <h3>每场景配齐六项治理</h3>
    <div class="grid2">
      {"".join(f'<div class="scc"><b>{a}</b><p>{b}</p></div>' for a, b in GOV_ZH)}
    </div>
    """
    body_en = f"""
    <h3>AI ecosystem map (conceptual)</h3>
    <p class="chain">{" → ".join(f"<b>{a}</b>" for a in CHAIN_EN)}</p>
    <p>Regional coordination (conceptual):</p>
    <table class="mt"><tr><th>Plate</th><th>Relation</th><th>Mechanism</th></tr>
    {"".join(f"<tr><td>{a}</td><td>{b}</td><td>{c}</td></tr>" for a, b, c in REGS_EN)}</table>
    <h3>12 scenario cards + 3 test scenarios</h3>
    <div class="grid2">
      {"".join(f'<div class="scc"><b>{a}</b><p>{b}</p></div>' for a, b in SCENARIOS_EN)}
    </div>
    <div class="metric-strip">
      {"".join(f"<span>{a} · {b}</span>" for a, b, c, d in SCEN_TEST_EN)}
    </div>
    <h3>Six governance dimensions per scenario</h3>
    <div class="grid2">
      {"".join(f'<div class="scc"><b>{a}</b><p>{b}</p></div>' for a, b in GOV_EN)}
    </div>
    """
    P.append(page("AI生态图谱与场景体系", "AI Ecosystem & Scenarios", body, body_en, no=6))

    # ---- P7 inclusivity ----
    body = f"""
    <p>包容性设计覆盖六类画像，全部数字场景提供线下等价服务与算法申诉渠道，并执行年度第三方人工可访问性检查（概念建议）。</p>
    <table class="mt"><tr><th>画像</th><th>典型需求</th><th>线下等价服务/自检边界</th></tr>
    {"".join(f"<tr><td>{a}</td><td>{b}</td><td>{c}</td></tr>" for a, b, c in PERSONAS_ZH)}</table>
    <h3>四项机制</h3>
    <div class="grid2">
      {"".join(f'<div class="scc"><b>{a}</b><p>{b}</p></div>' for a, b in MECH_ZH)}
    </div>
    """
    body_en = f"""
    <p>Inclusive design covers six personas; every digital scenario provides offline equivalent services and an algorithm appeal channel, with an annual third-party manual accessibility inspection (conceptual).</p>
    <table class="mt"><tr><th>Persona</th><th>Typical needs</th><th>Offline equivalents / self-check boundary</th></tr>
    {"".join(f"<tr><td>{a}</td><td>{b}</td><td>{c}</td></tr>" for a, b, c in PERSONAS_EN)}</table>
    <h3>Four mechanisms</h3>
    <div class="grid2">
      {"".join(f'<div class="scc"><b>{a}</b><p>{b}</p></div>' for a, b in MECH_EN)}
    </div>
    """
    P.append(page("包容性设计", "Inclusive Design", body, body_en, no=7))

    # ---- P8 metrics evidence ----
    body = f"""
    <p>全部指标由 tools/recompute_metrics.py 按同一几何与 EPSG:4548 复算，图件与指标卡由同一数据源生成，正文数值同步一致。</p>
    <table class="mt"><tr><th>指标</th><th>单位</th><th>复算值</th><th>来源</th><th>置信度</th></tr>{metric_rows()}</table>
    {fig_block("metrics-evidence.png", "指标证据链：复算口径、来源图层与关键指标", "Metrics evidence chain: recompute scope, source layers, and key indicators")}
    """
    body_en = f"""
    <p>All metrics are recomputed by tools/recompute_metrics.py from the same geometry in EPSG:4548; figures, metric cards, and text use the same normative values.</p>
    <table class="mt"><tr><th>Metric</th><th>Unit</th><th>Recomputed value</th><th>Source</th><th>Confidence</th></tr>{metric_rows()}</table>
    {fig_block("metrics-evidence.en.png", "Metrics evidence chain: recompute scope, source layers, and key indicators", "指标证据链：复算口径、来源图层与关键指标")}
    """
    P.append(page("指标体系与证据链", "Metrics & Evidence Chain", body, body_en, no=8))

    # ---- P9 implementation & operation ----
    body = f"""
    <h3>更新项目清单（示例，依赖条件见正文）</h3>
    <table class="mt"><tr><th>项目</th><th>类型</th><th>主要依赖</th></tr>
    {"".join(f"<tr><td>{a}</td><td>{b}</td><td>{c}</td></tr>" for a, b, c in JZ_ZH)}</table>
    <h3>长期运营与转化（概念建议）</h3>
    <div class="grid2">
      {"".join(f'<div class="scc"><b>{a}</b><p>{b}</p></div>' for a, b in OPS_ZH)}
    </div>
    <h3>公共空间组件库（概念版）</h3>
    <div class="grid2">
      {"".join(f'<div class="scc"><b>{a}</b><p>{b}</p></div>' for a, b in COMP_ZH)}
    </div>
    """
    body_en = f"""
    <h3>Renewal project list (examples; dependencies in the report)</h3>
    <table class="mt"><tr><th>Project</th><th>Type</th><th>Key dependencies</th></tr>
    {"".join(f"<tr><td>{a}</td><td>{b}</td><td>{c}</td></tr>" for a, b, c in JZ_EN)}</table>
    <h3>Long-term operation and conversion (conceptual)</h3>
    <div class="grid2">
      {"".join(f'<div class="scc"><b>{a}</b><p>{b}</p></div>' for a, b in OPS_EN)}
    </div>
    <h3>Public-space component library (conceptual)</h3>
    <div class="grid2">
      {"".join(f'<div class="scc"><b>{a}</b><p>{b}</p></div>' for a, b in COMP_EN)}
    </div>
    """
    P.append(page("实施运营与更新", "Implementation & Operation", body, body_en, no=9))

    # ---- P10 copyright & assumptions ----
    body = f"""
    <h3>版权与来源（逐资产台账见 report/copyright_statement.md）</h3>
    <ul>
      <li>全部文字、表格、图件与指标由本方案自产或使用已清权的公开/组织方资料；不包含未授权第三方图片、照片、商标或字体。</li>
      <li>19 条来源登记于 sources.json：7 个全球案例（KINGS-CROSS、KENDALL-SQUARE、STATION-F、MARUNOUCHI、JURONG-LAKE-DISTRICT、PANGYO、HETAO）、5 项标准（MOHURD/MNR）与组织方资料。</li>
      <li>本方案按 COMMUNITY-DISPLAY-ONLY 许可提交：仅限竞赛评审展示，转载注明出处，禁止商用。</li>
    </ul>
    <h3>假设与风险（assumptions.json，共 7 条）</h3>
    <table class="mt"><tr><th>ID</th><th>内容</th></tr>
    {"".join(f"<tr><td>{a}</td><td>{b}</td></tr>" for a, b in ASSUMP_ZH)}</table>
    <p class="warn">{PROV_WARN_ZH} 场景与运营KPI为概念指标；遗产符号待确认；运营机制待授权。</p>
    """
    body_en = f"""
    <h3>Copyright and sources (asset-level ledger: report/copyright_statement.md)</h3>
    <ul>
      <li>All text, tables, figures, and metrics are self-produced or use cleared public/organizer materials; no unauthorized third-party images, photos, trademarks, or fonts.</li>
      <li>19 sources registered in sources.json: 7 global cases (KINGS-CROSS, KENDALL-SQUARE, STATION-F, MARUNOUCHI, JURONG-LAKE-DISTRICT, PANGYO, HETAO), 5 standards (MOHURD/MNR), and organizer materials.</li>
      <li>Submitted under COMMUNITY-DISPLAY-ONLY: competition review display only, attribution required, no commercial use.</li>
    </ul>
    <h3>Assumptions and risks (assumptions.json, 7 items)</h3>
    <table class="mt"><tr><th>ID</th><th>Statement</th></tr>
    {"".join(f"<tr><td>{a}</td><td>{b}</td></tr>" for a, b in ASSUMP_EN)}</table>
    <p class="warn">{PROV_WARN_EN} Scenario and operation KPIs are conceptual; heritage symbols pending clearance; operation mechanisms pending authorization.</p>
    """
    P.append(page("版权、来源与假设", "Copyright, Sources & Assumptions", body, body_en, no=10))
    return P


def build_boards():
    B = []
    # B1 concept & overview
    body = f"""
    <div class="bgrid">
      <div class="bfig">{fig_block("site-overview.png", "总览地图", "Overview map")}</div>
      <div class="bcol">
        <h3>一条联廊、三座月台、两股轨道</h3>
        <p>约9公里绿道联廊为历史与公共空间主轴；三座月台对应三处重点区域；两股轨道对应中关村服务轨与小月河场景轨。</p>
        <div class="metric-strip">
          <span>场地 {mfmt('site_area_sqm')}</span><span>绿地率 {mfmt('green_ratio')}</span>
          <span>公共空间占比 {mfmt('public_space_ratio')}</span><span>重点片区 {mfmt('key_area_count')} 处</span>
        </div>
        <p class="warn">{PROV_WARN_ZH}</p>
      </div>
    </div>"""
    body_en = f"""
    <div class="bgrid">
      <div class="bfig">{fig_block("site-overview.en.png", "Overview map", "总览地图")}</div>
      <div class="bcol">
        <h3>One gallery, three platforms, two tracks</h3>
        <p>The ≈9 km green corridor is the heritage and public-space spine; the three platforms are the key areas; the two tracks are the Zhongguancun service track and the Xiaoyuehe scenario track.</p>
        <div class="metric-strip">
          <span>Site {mfmt('site_area_sqm')}</span><span>Green {mfmt('green_ratio')}</span>
          <span>Public space {mfmt('public_space_ratio')}</span><span>Key areas {mfmt('key_area_count')}</span>
        </div>
        <p class="warn">{PROV_WARN_EN}</p>
      </div>
    </div>"""
    B.append(page("总体概念与总览地图", "Overall Concept & Overview", body, body_en, no=1))

    # B2 ecosystem & scenarios
    body = f"""
    <div class="bgrid2">
      <div class="bcol2">
        <h3>AI生态图谱（概念版）</h3>
        <p class="chain">{" → ".join(f"<b>{a}</b>" for a in CHAIN_ZH)}</p>
        <h3>12 场景卡</h3>
        <div class="grid2">
          {"".join(f'<div class="scc"><b>{a}</b><p>{b}</p></div>' for a, b in SCENARIOS_ZH)}
        </div>
        <h3>3 测试场景</h3>
        <table class="mt"><tr><th>测试场景</th><th>空间载体</th><th>验证内容</th><th>成熟度·周期·复核</th></tr>
        {"".join(f"<tr><td>{a}</td><td>{b}</td><td>{c}</td><td>{d}</td></tr>" for a, b, c, d in SCEN_TEST_ZH)}</table>
      </div>
      <div class="bcol2">
        <h3>六项治理（每场景）</h3>
        <div class="grid2">
          {"".join(f'<div class="scc"><b>{a}</b><p>{b}</p></div>' for a, b in GOV_ZH)}
        </div>
        <h3>区域协同（概念建议）</h3>
        <table class="mt"><tr><th>协同板块</th><th>协同机制</th></tr>
        {"".join(f"<tr><td>{a}</td><td>{c}</td></tr>" for a, b, c in REGS_ZH)}</table>
        <p class="warn">场景与运营KPI为概念指标，非承诺目标（A-SCENARIO-KPI-001）。</p>
      </div>
    </div>"""
    body_en = f"""
    <div class="bgrid2">
      <div class="bcol2">
        <h3>AI ecosystem map (conceptual)</h3>
        <p class="chain">{" → ".join(f"<b>{a}</b>" for a in CHAIN_EN)}</p>
        <h3>12 scenario cards</h3>
        <div class="grid2">
          {"".join(f'<div class="scc"><b>{a}</b><p>{b}</p></div>' for a, b in SCENARIOS_EN)}
        </div>
        <h3>3 test scenarios</h3>
        <table class="mt"><tr><th>Test scenario</th><th>Space carrier</th><th>Validation</th><th>Maturity · period · review</th></tr>
        {"".join(f"<tr><td>{a}</td><td>{b}</td><td>{c}</td><td>{d}</td></tr>" for a, b, c, d in SCEN_TEST_EN)}</table>
      </div>
      <div class="bcol2">
        <h3>Six governance dimensions (per scenario)</h3>
        <div class="grid2">
          {"".join(f'<div class="scc"><b>{a}</b><p>{b}</p></div>' for a, b in GOV_EN)}
        </div>
        <h3>Regional coordination (conceptual)</h3>
        <table class="mt"><tr><th>Plate</th><th>Mechanism</th></tr>
        {"".join(f"<tr><td>{a}</td><td>{c}</td></tr>" for a, b, c in REGS_EN)}</table>
        <p class="warn">Scenario and operation KPIs are conceptual indicators, not commitments (A-SCENARIO-KPI-001).</p>
      </div>
    </div>"""
    B.append(page("AI生态、场景与治理", "AI Ecosystem, Scenarios & Governance", body, body_en, no=2))

    # B3 key areas & public space
    ka_rows = "".join(
        f"<tr><td>{a}</td><td>{b}</td><td>{c:.1f} ha</td><td>{d:.1f} ha</td></tr>"
        for a, b, c, d in KEY_AREAS
    )
    body = f"""
    <div class="bgrid">
      <div class="bfig">{fig_block("key-areas.png", "三处重点区域索引与设计任务图", "Three key areas")}</div>
      <div class="bcol">
        <table class="mt"><tr><th>重点片区</th><th>设计定位</th><th>公告约面积</th><th>复算面积</th></tr>{ka_rows}
        <tr class="sum"><td colspan="2">合计 368.4 / 369.3 ha</td><td>368.4 ha</td><td>{mfmt('key_area_total_area_sqm')}</td></tr></table>
        <h3>公共空间组件库（概念版）</h3>
        <div class="grid2">
          {"".join(f'<div class="scc"><b>{a}</b><p>{b}</p></div>' for a, b in COMP_ZH)}
        </div>
        <h3>包容性设计（六类画像）</h3>
        <p>{" · ".join(a for a, b, c in PERSONAS_ZH)}——每场景提供线下等价服务、算法申诉渠道与年度第三方人工可访问性检查（A-ACCESSIBILITY-001）。</p>
      </div>
    </div>"""
    body_en = f"""
    <div class="bgrid">
      <div class="bfig">{fig_block("key-areas.en.png", "Three key areas index and design-task map", "三处重点区域")}</div>
      <div class="bcol">
        <table class="mt"><tr><th>Key area</th><th>Design position</th><th>Announced</th><th>Recomputed</th></tr>{ka_rows}
        <tr class="sum"><td colspan="2">Total 368.4 / 369.3 ha</td><td>368.4 ha</td><td>{mfmt('key_area_total_area_sqm')}</td></tr></table>
        <h3>Public-space component library (conceptual)</h3>
        <div class="grid2">
          {"".join(f'<div class="scc"><b>{a}</b><p>{b}</p></div>' for a, b in COMP_EN)}
        </div>
        <h3>Inclusive design (six personas)</h3>
        <p>{" · ".join(a for a, b, c in PERSONAS_EN)} — every scenario provides offline equivalents, an appeal channel, and an annual third-party accessibility inspection (A-ACCESSIBILITY-001).</p>
      </div>
    </div>"""
    B.append(page("重点区域与公共空间", "Key Areas & Public Space", body, body_en, no=3))

    # B4 implementation & metrics
    body = f"""
    <div class="bgrid2">
      <div class="bcol2">
        <h3>实施与运营</h3>
        <table class="mt"><tr><th>更新项目</th><th>类型</th></tr>
        {"".join(f"<tr><td>{a}</td><td>{b}</td></tr>" for a, b, c in JZ_ZH)}</table>
        <div class="grid2">
          {"".join(f'<div class="scc"><b>{a}</b><p>{b}</p></div>' for a, b in OPS_ZH)}
        </div>
        {fig_block("mobility-bluegreen.png", "交通慢行与蓝绿公共空间", "Mobility & blue-green")}
      </div>
      <div class="bcol2">
        <h3>指标证据链</h3>
        <table class="mt"><tr><th>指标</th><th>复算值</th></tr>
        {"".join(f"<tr><td>{lzh}</td><td>{mfmt(k)}</td></tr>" for k, lzh, len_, unit, src, conf in METRIC_LABELS)}</table>
        {fig_block("metrics-evidence.png", "指标证据链", "Metrics evidence")}
        <p class="warn">{PROV_WARN_ZH}</p>
        <p>{LICENSE_ZH}</p>
      </div>
    </div>"""
    body_en = f"""
    <div class="bgrid2">
      <div class="bcol2">
        <h3>Implementation and operation</h3>
        <table class="mt"><tr><th>Renewal project</th><th>Type</th></tr>
        {"".join(f"<tr><td>{a}</td><td>{b}</td></tr>" for a, b, c in JZ_EN)}</table>
        <div class="grid2">
          {"".join(f'<div class="scc"><b>{a}</b><p>{b}</p></div>' for a, b in OPS_EN)}
        </div>
        {fig_block("mobility-bluegreen.en.png", "Mobility & blue-green", "交通慢行与蓝绿公共空间")}
      </div>
      <div class="bcol2">
        <h3>Metrics evidence chain</h3>
        <table class="mt"><tr><th>Metric</th><th>Value</th></tr>
        {"".join(f"<tr><td>{len_}</td><td>{mfmt(k)}</td></tr>" for k, lzh, len_, unit, src, conf in METRIC_LABELS)}</table>
        {fig_block("metrics-evidence.en.png", "Metrics evidence", "指标证据链")}
        <p class="warn">{PROV_WARN_EN}</p>
        <p>{LICENSE_EN}</p>
      </div>
    </div>"""
    B.append(page("实施运营与指标证据", "Implementation & Metrics Evidence", body, body_en, no=4))
    return B


CSS_A3 = """
@page { size: 420mm 297mm; margin: 0; }
* { box-sizing: border-box; margin: 0; padding: 0; }
html, body { font-family: "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "Helvetica Neue", Arial, sans-serif; color: #1c1f26; }
.page { width: 420mm; height: 297mm; overflow: hidden; page-break-after: always; background: #fff; display: flex; flex-direction: column; -webkit-print-color-adjust: exact; }
.page:last-child { page-break-after: auto; }
.hdr { display: flex; align-items: baseline; gap: 12px; padding: 9mm 14mm 6mm; border-bottom: 1.4px solid #3B3F46; }
.hdr .brand { font-size: 15pt; font-weight: 700; letter-spacing: .5px; color: #3B3F46; }
.hdr .brand small { font-weight: 400; color: #6b7280; }
.hdr .ptitle { font-size: 15pt; font-weight: 600; }
.hdr .pno { margin-left: auto; font-size: 10.5pt; color: #6b7280; }
.body { flex: 1; padding: 8mm 14mm 6mm; overflow: hidden; }
.ftr { display: flex; justify-content: space-between; gap: 12px; padding: 4mm 14mm 5mm; border-top: 1px solid #d7dade; font-size: 8.2pt; color: #4b5563; }
.ftr .warn { color: #b45309; font-weight: 600; }
h3 { font-size: 13.5pt; margin: 4mm 0 2.5mm; color: #3B3F46; }
p { font-size: 10.5pt; line-height: 1.55; margin-bottom: 2.5mm; }
ul { font-size: 10pt; margin-left: 6mm; line-height: 1.6; }
figure { margin: 3mm 0; text-align: center; }
figure img { max-width: 100%; max-height: 176mm; }
figcaption { font-size: 8.5pt; color: #6b7280; margin-top: 1.5mm; }
table.mt { width: 100%; border-collapse: collapse; font-size: 9.3pt; margin: 2mm 0 3mm; }
table.mt th, table.mt td { border: 0.5px solid #c9cdd3; padding: 1.6mm 2.2mm; text-align: left; vertical-align: top; }
table.mt th { background: #eef1f4; font-weight: 600; }
table.mt tr.sum td { background: #fdf6e3; font-weight: 600; }
.metric-strip { display: flex; flex-wrap: wrap; gap: 6px; margin: 3mm 0; }
.metric-strip span { background: #eef1f4; border-left: 3px solid #3B3F46; padding: 1.8mm 4mm; font-size: 10pt; border-radius: 2px; }
.cover { text-align: center; padding-top: 18mm; }
.cover-kicker { font-size: 12pt; color: #6b7280; letter-spacing: 2px; }
.cover h1 { font-size: 44pt; margin: 10mm 0 4mm; color: #3B3F46; }
.cover h1 span { color: #2E7D57; }
.cover-sub { font-size: 14pt; max-width: 340mm; margin: 0 auto 9mm; }
.cover-cards, .grid3 { display: grid; grid-template-columns: repeat(3, 1fr); gap: 7mm; margin: 0 auto 8mm; }
.c3card { border: 1px solid #c9cdd3; border-top: 3px solid #2E7D57; padding: 5mm 6mm; text-align: left; background: #fafbfc; }
.c3card h4 { font-size: 12.5pt; margin-bottom: 2mm; color: #3B3F46; }
.c3card p { font-size: 10pt; margin: 0; }
.cover-note { font-size: 9pt; color: #b45309; max-width: 320mm; margin: 0 auto; }
.grid2 { display: grid; grid-template-columns: repeat(2, 1fr); gap: 3mm; }
.scc { border: 0.5px solid #d7dade; padding: 2.2mm 3mm; background: #fff; }
.scc b { font-size: 9.6pt; color: #3B3F46; }
.scc p { font-size: 8.8pt; margin: 1mm 0 0; color: #4b5563; }
.chain { font-size: 12pt; font-weight: 600; color: #2E7D57; margin: 2mm 0 4mm; }
.chain b { color: #3B3F46; }
.warn { color: #b45309; font-size: 9.5pt; }
"""

CSS_A0 = """
@page { size: 1189mm 841mm; margin: 0; }
* { box-sizing: border-box; margin: 0; padding: 0; }
html, body { font-family: "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "Helvetica Neue", Arial, sans-serif; color: #1c1f26; }
.page { width: 1189mm; height: 841mm; overflow: hidden; page-break-after: always; background: #fff; display: flex; flex-direction: column; -webkit-print-color-adjust: exact; }
.page:last-child { page-break-after: auto; }
.hdr { display: flex; align-items: baseline; gap: 24px; padding: 18mm 26mm 14mm; border-bottom: 2.5px solid #3B3F46; }
.hdr .brand { font-size: 34pt; font-weight: 700; color: #3B3F46; }
.hdr .brand small { font-weight: 400; color: #6b7280; font-size: 24pt; }
.hdr .ptitle { font-size: 34pt; font-weight: 600; }
.hdr .pno { margin-left: auto; font-size: 22pt; color: #6b7280; }
.body { flex: 1; padding: 14mm 26mm 12mm; overflow: hidden; }
.ftr { display: flex; justify-content: space-between; gap: 20px; padding: 8mm 26mm 10mm; border-top: 2px solid #d7dade; font-size: 16pt; color: #4b5563; }
.ftr .warn { color: #b45309; font-weight: 600; }
h3 { font-size: 27pt; margin: 8mm 0 5mm; color: #3B3F46; }
p { font-size: 20pt; line-height: 1.55; margin-bottom: 5mm; }
figure { text-align: center; }
figure img { width: 100%; max-width: 100%; max-height: 640mm; object-fit: contain; }
figcaption { font-size: 15pt; color: #6b7280; margin-top: 3mm; }
table.mt { width: 100%; border-collapse: collapse; font-size: 17pt; margin: 4mm 0 6mm; }
table.mt th, table.mt td { border: 0.8px solid #c9cdd3; padding: 3mm 4mm; text-align: left; vertical-align: top; }
table.mt th { background: #eef1f4; font-weight: 600; }
table.mt tr.sum td { background: #fdf6e3; font-weight: 600; }
.metric-strip { display: flex; flex-wrap: wrap; gap: 10px; margin: 6mm 0; }
.metric-strip span { background: #eef1f4; border-left: 5px solid #3B3F46; padding: 3.5mm 8mm; font-size: 20pt; border-radius: 3px; }
.bgrid { display: grid; grid-template-columns: 3fr 1.4fr; gap: 14mm; align-items: start; }
.bgrid2 { display: grid; grid-template-columns: 1fr 1fr; gap: 12mm; align-items: start; }
.bfig figure img { max-height: 660mm; }
.grid2 { display: grid; grid-template-columns: repeat(2, 1fr); gap: 5mm; }
.scc { border: 0.8px solid #d7dade; padding: 4mm 5mm; background: #fff; }
.scc b { font-size: 17pt; color: #3B3F46; }
.scc p { font-size: 15pt; margin: 1.5mm 0 0; color: #4b5563; }
.chain { font-size: 24pt; font-weight: 600; color: #2E7D57; margin: 4mm 0 8mm; }
.chain b { color: #3B3F46; }
.warn { color: #b45309; font-size: 17pt; }
"""


def render_pdf(html_path: Path, out_path: Path) -> None:
    cmd = [
        CHROME, "--headless", "--disable-gpu", "--no-pdf-header-footer",
        f"--print-to-pdf={out_path.as_posix()}", html_path.as_uri(),
    ]
    r = subprocess.run(cmd, capture_output=True, text=True, check=False)
    if r.returncode != 0 or not out_path.exists():
        sys.stderr.write(r.stderr[-3000:])
        raise SystemExit(f"chrome failed for {out_path.name}")


def build_html(pages, css: str, lang: str, size_label: str) -> str:
    parts = []
    for i, p in enumerate(pages):
        fig = p["f_zh"] if lang == "zh" else p["f_en"]
        body = p["b_zh"] if lang == "zh" else p["b_en"]
        title = p["t_zh"] if lang == "zh" else p["t_en"]
        total = len(pages)
        brand = "京张月台 JINGZHANG PLATFORM · 百年京张AI创新带城市设计"
        if lang == "en":
            brand = "JINGZHANG PLATFORM · Centennial Jingzhang AI Innovation Belt"
        parts.append(
            f'<div class="page">'
            f'<header class="hdr"><span class="brand">{brand}</span>'
            f'<span class="ptitle">{title}</span>'
            f'<span class="pno">{p["no"]:02d} / {total:02d}</span></header>'
            f'<main class="body">{body}</main>'
            f'<footer class="ftr"><span class="warn">{"临时几何 provisional" if lang == "zh" else "Provisional geometry"}：{"面积与比例按 EPSG:4548 复算，官方边界发布后须重算" if lang == "zh" else "areas/ratios recomputed in EPSG:4548; recompute when official polygons publish"} · 来源 { "sources.json / metrics.json / geometry" if lang == "zh" else "sources.json / metrics.json / geometry"}</span>'
            f'<span>{"数据来源与图件由本方案脚本生成，无第三方素材" if lang == "zh" else "Figures and data generated by this submission\\u2019s scripts, no third-party assets"}</span></footer></div>'
        )
    html_doc = f"<!DOCTYPE html><html lang=\"{lang}\"><head><meta charset=\"utf-8\"><title>{size_label}</title><style>{css}</style></head><body>{''.join(parts)}</body></html>"
    return html_doc


def main() -> int:
    if not os.path.exists(CHROME):
        print(f"ERROR: chrome not found at {CHROME}", file=sys.stderr)
        return 1
    out_dir = ROOT / "drawings"
    out_dir.mkdir(exist_ok=True)

    jobs = [
        ("a3-booklet", build_booklet_pages(), CSS_A3, "A3"),
        ("a0-boards", build_boards(), CSS_A0, "A0"),
    ]
    tmp = Path(tempfile.mkdtemp(prefix="jz-drawings-"))
    try:
        for stem, pages, css, size in jobs:
            for lang, suffix in (("zh", ""), ("en", ".en")):
                html_path = tmp / f"{stem}{suffix}.html"
                html_path.write_text(build_html(pages, css, lang, size), encoding="utf-8")
                pdf_path = out_dir / f"{stem}{suffix}.pdf"
                render_pdf(html_path, pdf_path)
                print(f"wrote {pdf_path.relative_to(ROOT)} ({pdf_path.stat().st_size // 1024} KiB)")
    finally:
        shutil.rmtree(tmp, ignore_errors=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
